config/routes.rb
Traxit::Application.routes.draw do

  get 'items/new' => 'items#new'
  get 'items/propitem/:property' => 'items#propitem'
  post 'items/create' => 'items#create'

  patch 'items/complete' => 'items#complete'
  patch 'items/reset' => 'items#reset'
  
  get 'items/service_add/:id' => 'items#service_add', :as => :service_add
  post 'items/service_create/:id' => 'items#service_create'

  get 'items/overview/:id' => 'items#overview', :as => :item_overview
  post 'items/update_manual' => 'items#update_manual'
  post 'items/assign_handler' => 'items#assign_handler'
  delete 'items/info/:id' => 'items#destroy'

  get 'items/new_field/:unique' => 'items#new_field'
  get 'items/properties/:id' => 'items#properties', :as => :properties
  post 'items/update_properties/:id' => 'items#update_properties'

  get 'items/image/:id' => 'items#image', :as => :item_image
  get 'items/big_image/:id/:num' => 'items#big_image', :as => :big_image
  get 'items/remove_image/:id/:num' => 'items#remove_image', :as => :remove_image
  post 'items/update_image' => 'items#update_image'

  get 'items/qr/:id' => 'items#qr', :as => :qr_code
  get 'items/info/:id' => 'items#info'
  get 'items/notes/:wid/:sid' => 'items#notes', :as => :notes
  get 'items' => 'items#list'

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def list
  	@widget_list = Widget.all
  end

  def create

    if params[:purchase] == ""
      flash[:notice] = 'Failed to Create Widget!  Must have purchase info!'
      flash[:status] = 'danger'
      redirect_to :back
    end

    w = Widget.create(params[:widget])
    w.properties = params[:properties]

    w.purchase['purchase_date'] = w.purchase['purchase_date'].to_time

    if w.save
      flash[:notice] = 'Created Widget'
      flash[:status] = 'success'

      redirect_to(:controller => 'items', :action => 'list')
    else
      flash[:notice] = 'Failed to Create Widget'
      flash[:status] = 'danger'

      redirect_to :back
    end

  end

  def info
  	@active_widget = Widget.find(params[:id])
  	@service_list = @active_widget.services.sort_by{|e| e[:start]}.reverse
  end

  def notes
  	@wid = params[:wid]
  	sid = params[:sid]

  	@active_widget = Widget.find(@wid)
  	@service = @active_widget.services.find(sid)

  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def service_add
  	@wid = params[:id]

  	# @simple_name = params[:simple_name]
  	# @active_widget = Widget.find(@wid)

  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def properties
  	wid = params[:id]

  	@active_widget = Widget.find(wid)

  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def service_create
  	# puts "Create #{params[:id]}"

  	w = Widget.find(params[:id])
  	s = Service.new(start: params[:start], short_description: params[:short_description], long_description: params[:long_description])

  	if w.services << s
  		flash[:notice] = 'Created Service Task'
  		flash[:status] = 'success'

  		redirect_to :back
  	else
  		flash[:notice] = 'Failed to add Service Task'
  		flash[:status] = 'danger'

  		redirect_to :back
  	end
  end

  def complete
  	wid = params[:wid]
  	sid = params[:sid]

  	active_widget = Widget.find(wid)
  	active_service = active_widget.services.detect {|s| s["_id"].to_s == sid }

  	# puts "Short Desc: #{active_service.short_description}"

  	active_service.completed = true
  	active_service.finish = params[:complete_date]

  	if active_service.save
	  	respond_to do |format|
	  		format.json { render json: {'something' => 'asdf'}, status: :ok }
	  	end
	  end
  end

  def reset
  	wid = params[:wid]
  	sid = params[:sid]

  	active_widget = Widget.find(wid)
  	active_service = active_widget.services.detect {|s| s["_id"].to_s == sid }

  	active_service.completed = false
  	active_service.unset(:finish)

  	if active_service.save
	  	respond_to do |format|
	  		format.json { render json: {'something' => 'asdf'}, status: :ok }
	  	end
	  end
  end

  def qr
  	respond_to do |format|
  		format.html
  		## Prod
  		# format.svg { render :qrcode => "#{request.protocol}#{request.host}:#{request.port}/items/info/#{params[:id]}", :level => :l, :unit => 10 }

  		## Dev
  		format.svg { render :qrcode => "#{request.protocol}#{request.host}:#{request.port}/items/info/#{params[:id]}", :level => :l, :unit => 10 }
  	end
  end

  def new_field
    render partial: 'items/new_field'
  end

  def update_properties
    active_widget = Widget.find(params[:id])

    puts "Current Properties: #{active_widget.properties}"

    props = ActiveSupport::JSON.decode(params[:props])
    puts "JSON: #{props}"

    active_widget.properties = props

    if active_widget.save
      respond_to do |format|
        format.json { render json: {'success' => true}, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: {'success' => false}, status: 500 }
      end
    end

  end

  def update_image

    if !Dir.exists?("public/media/#{params[:wid]}")
      Dir.mkdir "public/media/#{params[:wid]}"
    end

    uploaded_io = params[:image]

    last_image = Dir["public/media/#{params[:wid]}/*.jpg"].to_a.last
    last_file_number = /(\d).jpg/.match(last_image).to_a[1]
    file_count = last_file_number.to_i + 1

    image_thumb = MiniMagick::Image.read(uploaded_io)

    #image_thumb.resize "200x200"
    #image_thumb.write  "thumb-test.jpg"

    image_thumb = resize_and_crop(image_thumb, 150)

    image_thumb.write "public/media/#{params[:wid]}/#{file_count}-thumb.jpg"

    File.open(Rails.root.join('public', 'media', "#{params[:wid]}", "#{file_count}.jpg"), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    flash[:notice] = 'Created New Image'
    flash[:status] = 'success'

    redirect_to :back
  end

  def update_manual

    current_widget = Widget.find(params[:wid])

    uploaded_io = params[:service_manual]

    tmp_name = current_widget['simple_name'].gsub(/\'/,'')
    tmp_name = tmp_name.gsub(/\s/,'_')

    if !Dir.exists?("public/media/#{params[:wid]}")
      Dir.mkdir "public/media/#{params[:wid]}"
    end

    File.open(Rails.root.join('public', 'media', "#{params[:wid]}", "#{tmp_name}.pdf"), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    flash[:notice] = 'Uploaded Service Manual'
    flash[:status] = 'success'

    redirect_to :back
  end

  def big_image
    @image_info = Hash.new
    @image_info = {:wid => params[:id], :num => params[:num]}
  end

  def image
    @active_widget = params[:id]

    respond_to do |format|
      format.html
      format.js
    end
  end

  def remove_image
    wid = params[:id]
    num = params[:num]

    File.delete(Rails.root + "public/media/#{wid}/#{num}.jpg")
    File.delete(Rails.root + "public/media/#{wid}/#{num}-thumb.jpg")

    flash[:notice] = 'Removed Image'
    flash[:status] = 'danger'

    redirect_to :back
  end

  def propitem
    @property = params[:property]

    render partial: 'items/propitem'
  end

  def assign_handler
    new_handler = params[:assigned_handler].split(' ')
    active_widget = Widget.find(params[:wid])

    puts "New Handler: #{new_handler}"

    if params[:assigned_handler] == 'none'
      if active_widget.handler != nil
        active_widget.handler.destroy
        active_widget.save
      end

      flash[:notice] = 'Assigned to No One'
      flash[:status] = 'warning'

      redirect_to(:controller => 'items', :action => 'info', :id => active_widget.id)

    elsif active_widget.handler == nil
      h = Handler.new(first_name: new_handler[0], last_name: new_handler[1])
      active_widget.handler = h
      active_widget.save

      flash[:notice] = "Assigned to #{params[:assigned_handler]}"
      flash[:status] = 'success'

      redirect_to(:controller => 'items', :action => 'info', :id => active_widget.id)
    elsif active_widget.handler != nil
      if !active_widget.handler.check_name(new_handler[0], new_handler[1])
        h = Handler.new(first_name: new_handler[0], last_name: new_handler[1])
        active_widget.handler = h
        active_widget.save
      end

      flash[:notice] = "Assigned to #{params[:assigned_handler]}"
      flash[:status] = 'success'

      redirect_to(:controller => 'items', :action => 'info', :id => active_widget.id)
    else
      flash[:notice] = "I don't know what to do so I'm freaking out!!!"
      flash[:status] = 'danger'

      redirect_to(:controller => 'items', :action => 'info', :id => active_widget.id)
    end

  end

  def overview
    #@active_widget = Widget.find(params[:id])
    @active_widget = params[:id]

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    w = Widget.find(params[:id])

    if w.destroy
      flash[:notice] = 'Successfully Removed Widget!!'
      flash[:status] = 'success'
    else
      flash[:notice] = 'Widget could not be removed'
      flash[:status] = 'warning'
    end

    redirect_to controller: 'items', action: 'list'
  end

  private

  def resize_and_crop(image, size)
    if image[:width] < image[:height]
      remove = ((image[:height] - image[:width])/2).round
      image.shave("0x#{remove}")
    elsif image[:width] > image[:height]
      remove = ((image[:width] - image[:height])/2).round
      image.shave("#{remove}x0")
    end
    image.resize("#{size}x#{size}")
    return image
  end
end

app/helpers/items_helper.rb
module ItemsHelper
	def complete_label(completed)
		if completed
			return '<span class="label label-success">Completed</span>'
		else
			return '<span class="label label-warning">In Progress</span>'
		end
  end

  def image_num(image)
    return /(\d)-thumb.jpg/.match(image).to_a[1].to_i
  end

  def properties_map_reducer
    map = %q{
      function() {
        for (var key in this.properties) {
          emit(key, null);
        }
      }
    }

    reduce = %q{
      function(key, stuff) {
        return null;
      }
    }

    results = Widget.map_reduce(map, reduce).out(inline: true)

    property_list = Array.new

    results.each do |r|
      property_list.push(r["_id"])
    end

    return property_list
  end

  def people_map_reducer
    map = %q{
      function() {
        var name = "";
        if (this.handler === undefined) {
          emit(null, null);
        } else {
          for(var i in this.handler){
            name = this.handler['first_name'] + ' ' + this.handler['last_name'];
          }
          emit(name, null);
        }
      }
    }

    reduce = %q{
      function(key, stuff) {
        return null;
      }
    }

    results = Widget.map_reduce(map, reduce).out(inline: true)

    people_list = Array.new

    results.each do |r|
      if !r["_id"].nil?
        people_list.push(r["_id"])
      end
    end

    return people_list.sort
  end

end

app/views/items/_big_image.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-body">
      <div id="big-image-container">
        <%= link_to remove_image_path(:action => 'remove_image', :id => @image_info[:wid], :num => @image_info[:num]) do %>
          <button id="big-image-remove" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
        <% end %>
        <%= image_tag "/media/#{@image_info[:wid]}/#{@image_info[:num]}.jpg", class: 'img-thumbnail img-responsive' %>
      </div>
    </div> <!-- .modal-body -->
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/items/_completed.html.erb
<div class="modal-body">
  <div class="alert alert-danger notes-alert" hidden>Oh Snap, an alert!</div>
  <h4>Long Description:</h4>
  <p><%= @service.long_description %></p>
	<h5>Completed On:</h5>
	<p><%= @service.finish %></p>

</div> <!-- .modal-body -->
<div class="modal-footer">
  <button id="reset-btn" type="button" class="btn btn-danger">Reset Completion</button>
  <button type="button" class="btn btn-default" data-dismiss="modal">Dismiss</button>
</div> <!-- .modal-footer -->

app/views/items/_image.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Image</h4>
    </div>
    <div class="modal-body">
      <%= form_tag({action: :update_image}, multipart: true, method: "POST") do %>
        <%= label_tag(:image, "Choose Image to upload: ") %>
        <%= file_field_tag(:image) %>
        <%= hidden_field_tag(:wid, @active_widget) %>
        <hr/>
        <%= submit_tag("Upload", class: "btn btn-primary") %>
      <% end %>
    </div> <!-- .modal-body -->
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/items/_new_field.html.erb
<li class="prop-item">
  <div class="form-group">
    <div class="col-sm-3">
      <input type="text" id="new-key-<%= params[:unique] %>" name="new-key-<%= params[:unique] %>" class="form-control" placeholder="Field Key">
    </div>

    <div class="col-sm-9">
      <input type="text" id="new-value-<%= params[:unique] %>" name="new-value-<%= params[:unique] %>" class="form-control" placeholder="Field Value">
    </div> <!-- .col-sm-10 -->
  </div> <!-- .form-group -->
</li>

app/views/items/_overview.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Overview</h4>
    </div> <!--.modal-header-->
    <div class="modal-body">

      <div class="alert alert-warning" hidden>
        <p id="alert-message"></p>
      </div> <!--.alert-->

      <ul>

        <li>
          <label for="service-manual-cb">Service Manual</label>
          <input type="checkbox" name="service-manual-cb" id="service-manual-cb"/>
          <div class="service-manual" hidden>
            <%= form_tag({action: :update_manual}, multipart: true, method: "POST") do %>
              <%= label_tag(:service_manual, "Choose service manual to upload: ") %>
              <%= file_field_tag(:service_manual) %>
              <%= hidden_field_tag(:wid, @active_widget) %>
              <br/>
              <%= submit_tag("Upload", class: "btn btn-primary") %>
            <% end %>
          </div> <!--div.service-manual-->
        </li>

        <li>
          <label for="handler-cb">Assign Handler</label>
          <input type="checkbox" name="handler-cb" id="handler-cb"/>
        </li>

          <div class="handler" hidden>

            <%= form_tag({action: :assign_handler}, method: "POST") do %>
              <div class="radio">
                <label>
                  <input type="radio" name="handler-radio" id="optionsRadios1" checked>
                  <input type="hidden" value="none"/>
                  No One
                </label>
              </div>

              <div class="radio">
                <%= render partial: 'handler_select' %>
              </div>

              <div class="radio">
                <label>
                  <input type="radio" name="handler-radio" id="optionsRadios3" value="option3">
                  <input type="text" name="" class="form-control" id="new-handler-text" placeholder="John Doe" style="width: 50%;">
                </label>
              </div>

              <input type="hidden" id="assigned-handler" name="assigned_handler" value=""/>
              <%= hidden_field_tag(:wid, @active_widget) %>

              <button class="btn btn-primary" id="assign-btn">Assign</button>

            <% end %>
          </div> <!--div.handler-->

      </ul>

    </div> <!-- .modal-body -->
    <div class="modal-footer">
      <%= button_to "Delete Widget", @active_widget, data: {confirm: 'Are you sure you want to remove this widget?'}, :method => :delete, class: 'btn btn-danger pull-left' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div> <!--.modal-footer-->
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

<script>
  $('#service-manual-cb').change(function(){
    $('div.service-manual').toggle('fast');
  });

  $('#handler-cb').change(function(){
    $('div.handler').toggle('fast');
  });

  $('#assign-btn').click(function(event){

    var nv = $('input[name=handler-radio]:checked').next().val();
    console.log('Next Value: ' + nv);

    if(nv == '') {
      $('#alert-message').text("Please Enter a Handler's Name!");
      $('div.alert-warning').toggle('fast');
      event.preventDefault();
    }
    $('#assigned-handler').val(nv);

  });
</script>

app/views/items/_propitem.html.erb
<div class="form-group">
  <label for="<%= @property %>" class="col-lg-2 control-label"><%= @property %></label>
  <div class="col-lg-10">
    <input type="text" class="form-control" name="properties[<%= @property %>]" id="<%= @property %>>">
  </div>
</div>

app/views/items/_service_add.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">New Service Action</h4>
    </div>
    <div class="modal-body">
      <%= form_tag({controller: 'items', action: 'service_create', id: @wid}, method: 'post') do %>
        <div class="form-group">
          <label for="short_description">Short Description</label>
          <input type="text" class="form-control" id="short_description" name="short_description" placeholder="Enter quick description" required>
        </div> <!-- short description -->
        <div class="form-group">
          <label for="long_description">Long Description</label>
          <textarea name="long_description" id="long_description" rows="4" class="form-control" placeholder="Enter a detailed description of the service work" required></textarea>
        </div> <!-- long description -->
        <div class="form-group">
          <label for="start">Start Date</label>
          <input type="date" class="form-control" id="start" name="start" required>
        </div> <!-- start date -->

        </div> <!-- .modal-body -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag("Create Service Task", class: "btn btn-primary") %>
        </div> <!-- .modal-footer -->
      <% end %>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/items/big_image.js.erb
$('#big-image-modal').modal('show');
$("#big-image-modal").html("<%= escape_javascript(render 'items/big_image') %>");

app/views/items/image.js.erb
$('#image-modal').modal('show');
$("#image-modal").html("<%= escape_javascript(render 'items/image') %>");

app/views/items/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <% if !flash[:notice].blank? %>
      <div class="alert alert-<%= flash[:status] %> alert-dismissable">
        <div class="container">
          <%= flash[:notice] %>
        </div> <!-- .container -->
      </div> <!-- .alert -->
    <% end %>
  </div> <!-- .col-lg-12 -->
</div> <!-- .row -->

<div class="page-header">
  <h2>Create Widget</h2>
</div>

<%= form_for( @new_widget = Widget.new, url: {controller: 'items', action: 'create'}, method: 'post', html: {class: "form-horizontal"}) do |f| %>
<div class="row">
  <div class="col-lg-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Basic Information</h3>
      </div> <!-- .panel-heading -->

      <div class="panel-body">
        <div class="form-group">
          <%= f.label(:simple_name, "Short Name", class: "control-label col-lg-3") %>
          <div class="col-lg-9">
            <%= f.text_field( :simple_name, class: "form-control") %>
          </div> <!-- .col-lg-9 -->
        </div> <!-- short name .form-group -->

        <div class="form-group">
          <%= f.label(:description, "Description", class: 'control-label col-lg-3') %>
          <div class="col-lg-9">
            <%= f.text_area( :description, class: 'form-control') %>
          </div> <!-- .col-lg-9 -->
        </div> <!-- description .form-group -->

      </div> <!-- .panel-body -->
    </div> <!-- basic info .panel -->
  </div> <!-- .col-lg-6 -->

  <div class="col-lg-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Purchase Information</h3>
      </div> <!-- panel-heading -->
      <div class="panel-body">

        <%= f.fields_for :purchase do |p| %>
          <div class="form-group">
            <%= p.label(:price, "Price", class: 'control-label col-lg-3') %>
            <div class="col-lg-9">
              <%= p.text_field(:price, value: '0' ,class: 'form-control', type: 'number') %>
            </div> <!-- .col-lg-9 -->
          </div> <!-- price .form-group -->

          <div class="form-group">
            <%= p.label(:purchase_date, class: 'control-label col-lg-3') %>
            <div class="col-lg-9">
              <%= p.date_field(:purchase_date, value: Date.today, class: 'form-control') %>
            </div> <!-- .col-lg-9 -->
          </div> <!-- purchase_date .form-group -->
        <% end %>

      </div> <!-- .panel-body -->
    </div> <!-- purchase .panel -->
  </div> <!-- .col-lg-6 -->

</div> <!-- .row -->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Properties: <small>Select</small></h3>
        <select id="props">
          <option value=""></option>
          <% properties_map_reducer.each do |props| %>
            <option value="<%= props %>"><%= props %></option>
          <% end %>
          <option value="new-property">+ New Property</option>
        </select>
      </div> <!-- panel-heading -->

      <div class="panel-body">

        <div id="props-list"></div>

      </div> <!-- .panel-body -->

    </div> <!-- .panel -->
  </div> <!-- .col-lg-12 -->
</div> <!-- .row -->

<div class="row">
  <div class="col-lg-12">
    <%= f.submit "Create", id: "create-btn", class: 'btn btn-primary pull-right' %>
  </div> <!--.col-lg-12-->
</div> <!--.row-->

<% end %>

<script>

  function getPropsEntry(prop) {
    var results;

    $.ajax({
      async: false,
      url: '/items/propitem/' + prop,
      type: 'GET',
    }).done(function(e){
//      console.log(e);
      console.log('Success!');

      results = e;
    }).fail(function(e){
      console.log(e);
      console.log('Error!!');
    });

    return results;
  }

  $('#props').change(function() {

    var selected_prop = $('#props option:selected').prop('value');
    $('#props option:selected').remove();

//    console.log(selected_prop);

    var prop_item = getPropsEntry(selected_prop);

//    console.log(prop_item);

    $('#props-list').append(prop_item);
  });
</script>

app/views/items/notes.js.erb
$('#notes-modal').modal('show');
$("#notes-modal").html("<%= escape_javascript(render 'items/notes') %>");

app/views/items/overview.js.erb
$('#overview-modal').modal('show');
$("#overview-modal").html("<%= escape_javascript(render 'items/overview') %>");

app/views/items/properties.js.erb
$('#properties-modal').modal('show');
$("#properties-modal").html("<%= escape_javascript(render 'items/properties') %>");

app/views/items/service_add.js.erb
$('#service-add-modal').modal('show');
$("#service-add-modal").html("<%= escape_javascript(render 'items/service_add') %>");